// <auto-generated />
using ControleGastos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleGastos.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311232221_CreateTabelaPessoa")]
    partial class CreateTabelaPessoa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleGastos.Domain.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_CATEGORIA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("TX_DESCRICAO");

                    b.Property<int>("Finalidade")
                        .HasColumnType("int")
                        .HasColumnName("TX_FINALIDADE");

                    b.HasKey("Id");

                    b.ToTable("T_CATEGORIAS", (string)null);
                });

            modelBuilder.Entity("ControleGastos.Domain.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_PESSOA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("QT_IDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TX_PESSOA");

                    b.HasKey("Id");

                    b.ToTable("T_PESSOAS", (string)null);
                });

            modelBuilder.Entity("ControleGastos.Domain.Transacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_TRANSACAO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("CATEGORIA_ID");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("TX_DESCRICAO");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("PESSOA_ID");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TX_TIPO_TRANSACAO");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("QT_VALOR");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("T_TRANSACOES", (string)null);
                });

            modelBuilder.Entity("ControleGastos.Domain.Transacao", b =>
                {
                    b.HasOne("ControleGastos.Domain.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleGastos.Domain.Pessoa", "Pessoa")
                        .WithMany("Transacoes")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ControleGastos.Domain.Categoria", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("ControleGastos.Domain.Pessoa", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
